teamName: team-a
appName: kcd-demo
repoUrl: https://github.com/suxess-it/team-a-kcd-demo
createAppNamespace: true
stages:
  - name: "test"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        direct: true
  - name: "qa"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - test
  - name: "prod"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - qa
